env: # Environt variable to pass to all tasks
  CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
  CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
  ROM_FOLDER: "/tmp/rom" # Where rom is synced
  RCLONE_CONFIG_FILE: "ENCRYPTED[18b9c678d92190c26247d66300512f76407b06d2f78ef5c893970155df8e607c87469444c3349bed89aea30dee459a35]"
  BOT_TOKEN: "ENCRYPTED[0db16e928a3ddd29828143cd6673362baa9c4299fce69e7065626deeabca445afb14fb62ab517c73da5546e15e31a504]"

task:
  name: Rom-Builder
  timeout_in: 120m # Timeout in minutes, max 120 for free users
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 48G
  info_dump_script: bash info_dump # Has some important setup stuff for Rom-Builder!
  download_ccache_script: bash download_ccache
  sync_script: bash sync
  clone_devicestuff_script: bash devicestuff
  build_script: bash build
  build_rom_artifacts: # max 1GB total for free users, needs artifacts in working directory atm
    path: "build_artifacts/*"
#    type: application/zip
#  build_ota_json_artifacts:
#    path: "build_artifacts/tissot.json"
#    type: application/json
#  build_ota_changelog_artifacts:
#    path: "build_artifacts/changelog_tissot.txt"
 #   type: text/plain
#  upload_files_script: bash upload_files
  upload_ccache_script: bash upload_ccache
