env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    BOT_TOKEN: ENCRYPTED[8a491f640c3e261353ace025117f33ac84f9bb571024634ada04505ff32eef9c7365ea77b2d491b2f889529a2aa5ff4e]

task:
    name: Rom-Builder
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 16
      memory: 24G
    aosp_ccache_cache:
      folder: /tmp/ccache
      reupload_on_changes: true # since there is a fingerprint script
      fingerprint_script:
        - mkdir /tmp/ccache
#    download_ccache_script:
#      - bash download_ccache
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_ccache_script:
      - bash upload_files
#    upload_ccache_script:
#      - ./upload_ccache
