#!/bin/bash

mkdir /tmp/ci/build_artifacts
cd /tmp/rom

# Normal build steps
source build/envsetup.sh
export BUILD_TYPE=UNOFFICIAL
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
#ccache -o compression=true
ccache -z
lunch dot_tissot-user

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	mka bacon -j16
}

make_metalava
make_rom

# Copy build artifacts to ci dir for uploading on ci
cp out/target/product/tissot/*.zip /tmp/ci/build_artifacts/
#cp out/target/product/tissot/*.md5 /tmp/ci/build_artifacts/
