#!/bin/bash
# Clone device stuff and other extra repos
cd /tmp/rom # Depends on where source got syncedrm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur
# Trees
echo "Cloning device side stuff!"
git clone https://github.com/crdroidandroid/android_device_xiaomi_tissot.git -b 11.0 device/xiaomi/tissot --single-branch --depth=1
#git clone https://github.com/Devel-Zone/android_device_xiaomi_tissot.git -b 11.0 device/xiaomi/tissot --single-branch --depth=1
#git clone https://github.com/crdroidandroid/android_device_xiaomi_msm8953-common-tissot.git -b 11.0 device/xiaomi/msm8953-common --single-branch --depth=1
git clone https://github.com/Devel-Zone/android_device_xiaomi_msm8953-common-tissot.git -b 11.0 device/xiaomi/msm8953-common --single-branch --depth=1
git clone https://github.com/crdroidandroid/android_kernel_xiaomi_tissot.git -b 11.0 kernel/xiaomi/msm8953 --single-branch --depth=1
git clone https://gitlab.com/MASTERGUY/proprietary_vendor_xiaomi.git -b eleven vendor/xiaomi --single-branch --depth=1
