#!/bin/bash

cd /tmp/rom # Depends on where source got syncedrm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Clone extra repos, device side repos and extra ones
# Trees
echo "Cloning device side stuff!"
git clone https://github.com/crdroidandroid/android_device_xiaomi_tissot.git -b 11.0 device/xiaomi/tissot --single-branch --depth=1
#git clone https://github.com/Devel-Zone/android_device_xiaomi_tissot.git -b 11.0 device/xiaomi/tissot --single-branch --depth=1
#git clone https://github.com/crdroidandroid/android_device_xiaomi_msm8953-common-tissot.git -b 11.0 device/xiaomi/msm8953-common --single-branch --depth=1
git clone https://github.com/Devel-Zone/android_device_xiaomi_msm8953-common-tissot.git -b 11.0 device/xiaomi/msm8953-common --single-branch --depth=1
git clone https://github.com/crdroidandroid/android_kernel_xiaomi_tissot.git -b 11.0 kernel/xiaomi/msm8953 --single-branch --depth=1
git clone https://gitlab.com/MASTERGUY/proprietary_vendor_xiaomi.git -b eleven vendor/xiaomi --single-branch --depth=1
#Hals
#rm -rf hardware/qcom-caf/msm8996/audio hardware/qcom-caf/msm8996/display hardware/qcom-caf/msm8996/media
#git clone https://github.com/crdroidandroid/android_hardware_qcom_audio -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/audio --single-branch --depth=1
#git clone https://github.com/crdroidandroid/android_hardware_qcom_display -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/display --single-branch --depth=1
#git clone https://github.com/crdroidandroid/android_hardware_qcom_media -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/media --single-branch --depth=1
