#!/bin/bash
# Download ccache
cd /tmp # Where to download cccahe
rclone copy rc-servera1:Public_Folder/ccache/tissot/crdroid/ccache.tar.gz $PWD -P
ls -lh ccache.tar.gz
time tar xf ccache.tar.gz
ls -lh /tmp/ccache/
find ccache.tar.gz -delete
