#!/bin/bash
# Setup for builder
mkdir -p ${ROM_FOLDER}
mkdir -p ${CIRRUS_WORKING_DIR}/build_artifacts
mkdir -p ~/.config/rclone
printenv RCLONE_CONFIG_FILE > ~/.config/rclone/rclone.conf

# Lets see machine specifications and environments
echo "CPUs: "
nproc --all
echo " "
echo "RAM: "
free -h
echo " "
echo "Diskusage: "
df -h
echo " "
echo "Enviornment: "
cat /etc/os*
echo " "
env
