#!/bin/bash
# Additional deps
echo "Installing additional deps..."
sudo apt install wget
sudo apt remove rclone -y
cd /tmp
wget https://downloads.rclone.org/v1.54.1/rclone-v1.54.1-linux-amd64.deb
sudo dpkg -i rclone-v1.54.1-linux-amd64.deb
echo " "

# Setup for builder
mkdir -p ${ROM_FOLDER}
mkdir -p ${CIRRUS_WORKING_DIR}/build_artifacts
mkdir -p ~/.config/rclone
printenv RCLONE_CONFIG_FILE > ~/.config/rclone/rclone.conf

# Lets see machine specifications and environments
echo "CPUs: "
nproc --all
echo " "
echo "RAM: "
free -h
echo " "
echo "Diskusage: "
df -h
echo " "
echo "Enviornment: "
cat /etc/os*
echo " "
env
