#!/bin/bash
# Upload files
mkdir -p ~/.config/rclone
printenv RCLONE_CONFIG_SERVERA1 > ~/.config/rclone/rclone.conf
cd /tmp/rom
time rclone copy out/target/product/tissot/crDroidAndroid-*.zip rc-servera1:Public_Folder/Ashu/Others
echo " "
echo "https://server-a1.sohil876.workers.dev/0:/Ashu/Others/$FILENAME"
