#!/bin/bash

cd /tmp
# Show ccache stats
ccache -s
# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -1 " -cf $1.tar.gz $1
}

time com ccache # Compression level 1, its enough
mkdir -p ~/.config/rclone
echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
time rclone copy ccache.tar.gz rc-servera1:ccache/ -P
